services:
  - type: web
    name: saini-txt-direct
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/nikhilsainiop/Saini-txt-direct
    branch: main
    autoDeploy: false
    envVars:
      - key: 8557949406:AAGW3kwEH01FDPVjLNa1hSkx-F1jyjqC-ig
        sync: false
      - key: 27433400
        sync: false
      - key: 1a286620de5ffe0a7d9b57e604293555
        sync: false
      - key: 6201066540
        sync: false
      - key: Apnilife_1505_bot
        sync: false
      #- key: WEBHOOK
        #sync: True
      - key: PORT
        value: 8000  # Default port value, update if needed
